### ISSUE TITLE
REST API docs?

### ISSUE THREAD

**Issue by geoidesic** [parautenbach/Vodacom-Data-Usage#1]
Hi,

Great idea! I'd like to write my own implementation. How did you discover the API? 
Any docs / notes about the API would be appreciated!

I tried a basic Postman POST of username and password to https://www.vodacom.mobi (as defined in your config) but it didn't work. Do you perhaps have a Postman config you could share for testing the API?

Thanks!

**Comment by parautenbach** [comment]
Hello

Thank you.

I set up a proxy with [Wireshark](https://www.wireshark.org/) on my home network and configured my phone to connect to the internet via that proxy. You'll then get a TLS/SSL warning on your phone, in which case you need to read [this post](http://security.stackexchange.com/questions/64814/how-to-get-private-key-used-to-decrypt-https-traffic-sent-and-received-from-my-o). 

You won't be able to log in by directly POSTing to the host. Check the `log_in` and `get_data` functions in my code. The two resources are:
- login: `/coza_rest_10_0/basicauth`
- getting data info: `/coza_rest_10_0/balances?msisdn={0}&token={1}&linkedmsisdn={2}` 

If you have only one contract, the MSISDN and linked MSISDN will be the same, otherwise the MSISDN is your login/main MSISDN and linked MSISDN the secondary contract linked to the former. Either way, the linked MSISDN is the one you're retrieving info for. <rant>Technically, an MSISDN must be in international format, e.g. `+2782...`, but it seems like the Vodacom experts don't know that.</rant>

Upon login you'll receive a token in the response, and that's the token to use in the resource for getting data info (above). Also capture the received cookie and send that with every subsequent request. 

Also, the API is versioned, so you need to send some kind of (seemingly) valid user agent in the headers (e.g. `myvodacom/333 CFNetwork/672.1.15 Darwin/14.0.0`). You can capture this while capturing network traffic, but be aware that the API may reject calls in case they upgrade the API. 

I don't have Postman config, sorry, but I hope this helps! :-)

The main reason for building this little widget is that I have an internet gateway with a dongle that provides backup internet to my home network, so can't (won't) use the crappy Vodacom software.

**Comment by parautenbach** [comment]
I'm closing this, but feel free to ask if you have more questions.
